sudo: false

language:
  - php
  - node_js

before_script:
  - curl -s https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar > /tmp/wp-cli.phar

script:
  - echo "Deploy only"

before_deploy:
  - export RELEASE_FOLDER=stout
  - php /tmp/wp-cli.phar package install git@github.com:wp-cli/dist-archive-command.git
  - cp -rv ${TRAVIS_BUILD_DIR} /tmp/${RELEASE_FOLDER}
  - mv /tmp/${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}
  - php /tmp/wp-cli.phar dist-archive ${RELEASE_FOLDER} ${TRAVIS_BUILD_DIR}/${RELEASE_FOLDER}.zip --format=zip --debug

deploy:
  provider: releases
  api_key:
    secure: fjihUUnxFuY1/GkgFuCWgYpp9cymSG4VzPCXMG3xso5XX45qBIdzqgDxrIcWHkswwb72O7RZnWRq4rYYsIfmB/2gxJxuwJglEsSegjJqHnxVBsjhBjZgvX/ooitOdCL3Lb9fJCwY2uKD2hMov6XmNv+U+XzNO5raYXxy32L+D6+9nHBSq97oIrtaOfjpX9fcd9MU2whJgWGUPkePu2/V+2wMroeG5ZTC4Dcg47g4Oir4ccdhDWgNOFs3SOVhlzQyHW9DFVtfAAYj86B1Oi0mUZGpYVBSQC4ygxtyGYQEsO7sTZu5jb2TPDSp+oziDYZ9+7JEEUQjsd5BJ++tsBDeKLUaZFzJBAWha1YmnsNW2PRvcfbTugYK9hxf6sEQY1Jm3BaGTDS4qG/PQ1csDQhqlC5Cz0wJ/ETp8b2JvqMaajSeBWhSZtlt5/04R73UNYDPKRxuqN6Qv4xADY9OMSG20YKYy1Nr/5oQx/gRahtyS9saLUGi3ZTGC1oAhqytdjc9Ot/fsxriBMARIekXdznKpGcmYCzU8hKZg59WLZjqHA0CvDR6XHuNmBTAnTrI+THmFtDrqjL9riVogTbjXczb8Mji6sq95R6X97viYLM3M8y3Fpar9l1UZW+jarpqdlssfcU8HcUD4oH0/fzRYM5o6RiJgBYkdbmuewh+Zgx9QHI=
  file: stout.zip
  on:
    tags: true
    repo: godaddy/wp-stout-theme
  skip_cleanup: true
  overwrite: true
